### PR TITLE
if skipgravityonboot set, check db version.

### LINKED ISSUE #1398: [development-v6]:
### Versions

- Pi-hole:  development-v6
- AdminLTE:  development-v6
- FTL:  development-v6

### Platform

- OS and version:  Alpine 3.18

- Platform:  docker

### Expected behavior

_A clear and concise description of what you expected to happen._
Domain should be listed

### Actual behavior / bug
Domain is not listed:"Loading..." is always displayed.

_A clear and concise description of what the bug is._
pihole-FTL cannot fetch information from sql3 database.
```
pihole-pihole-1  | 2023-07-25 08:05:02.491 [193/T204] ERR: gravityDB_readTable(10 => (N/A)) - SQL error prepare (1): SELECT id,address,enabled,date_added,date_modified,comment,(SELECT GROUP_CONCAT(group_id) FROM adlist_by_group g WHERE g.adlist_id = a.id) AS group_ids,date_updated,number,invalid_domains,status,abp_entries FROM adlist a; => no such column: abp_entries
pihole-pihole-1  | 2023-07-25 08:05:02.491 [193/T204] WARNING: API: Could not read domains from database table (no such column: abp_entries)
```
### Steps to reproduce

1. Go to 'https://pihole.net/admin/groups/adlists'
3. Scroll down to 'List of adlists '

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._
image

### Additional context

_Add any other context about the problem here._
I was using pihole bundle in its latest version : Pi-hole v5.17.1 FTL v5.23 Web Interface v5.20.1 through docker-pi-hole image.
I then build and ran docker-pi-hole image with pihole-FTL base on branch development-v6.

I may have overlooked setup steps when using this version.
I realize that pihole-ftl v6 is still in his early stage and migration procedure might not be developped yet.
feel free to close this issue, if this is already known and not planned for the moment.

I've edited the gravity.db to add the missing columns, all seem ok.
`ALTER TABLE adlist ADD abp_entries INTEGER DEFAULT (0);`

### PR DESCRIPTION
**Pull request by edgd1er**
during pihole -g version is checked and db updated if needed.

## Description

At boot time either run pihole -g or check and upgrade database structure if needed.

## Motivation and Context

Updating everyday or at every start lists may be of little use and harsh on lists servers.
Allowing to bypass update at boot time, speed up the start and avoid traffic on lists servers.
Some lists are on github servers, too many accesses may trigger ban rules.

Fix #1398 

When SKIPGRAVITYONBOOT is not set (default), pihole -g runs at boot time.
it checks database's version and upgrade it if needed.

SKIPGRAVITYONBOOT allows to bypass the "pihole -g" step, hence database version is not checked anymore, lists are not updated.
Depending on the last update, incorrect version will cause many errors in the admin website.

## How Has This Been Tested?

I copied v5 databases to v6 container's volumes, an checked that database structure was updated and lists were not.

```
docker-pi-hole-pihole-1  | + gravityDBfile=/etc/pihole/gravity.db
docker-pi-hole-pihole-1  | + '[' -n true ']'
docker-pi-hole-pihole-1  | + '[' -f /etc/pihole/gravity.db 
docker-pi-hole-pihole-1  | ']'
docker-pi-hole-pihole-1  |   Skipping Gravity Database Update.
docker-pi-hole-pihole-1  | + echo '  Skipping Gravity Database Update.'
docker-pi-hole-pihole-1  | + source /opt/pihole/utils.sh
docker-pi-hole-pihole-1  | + source /etc/.pihole/advanced/Scripts/database_migration/gravity-db.sh
docker-pi-hole-pihole-1  | ++ readonly scriptPath=/etc/.pihole/advanced/Scripts/database_migration/gravity
docker-pi-hole-pihole-1  | ++ scriptPath=/etc/.pihole/advanced/Scripts/database_migration/gravity
docker-pi-hole-pihole-1  | + upgrade_gravityDB /etc/pihole/gravity.db /etc/pihole
docker-pi-hole-pihole-1  | + local database 
docker-pi-hole-pihole-1  | piholeDir 
docker-pi-hole-pihole-1  | auditFile version
docker-pi-hole-pihole-1  | + database=/etc/pihole/gravity.db
docker-pi-hole-pihole-1  | + 
docker-pi-hole-pihole-1  | piholeDir=/etc/pihole
docker-pi-hole-pihole-1  | + auditFile=/etc/pihole/auditlog.list
docker-pi-hole-pihole-1  | ++ pihole-FTL sqlite3 /etc/pihole/gravity.db 'SELECT "value" FROM "info" WHERE "property" = '\''version'\'';'
docker-pi-hole-pihole-1  | + version=16
docker-pi-hole-pihole-1  | + [[ 16 == \1 ]]
docker-pi-hole-pihole-1  | + [[ 16
docker-pi-hole-pihole-1  |  == 
docker-pi-hole-pihole-1  | \2 ]]
docker-pi-hole-pihole-1  | + [[ 
docker-pi-hole-pihole-1  | 16 == \3 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \4 ]]
docker-pi-hole-pihole-1  | + 
docker-pi-hole-pihole-1  | [[ 16
docker-pi-hole-pihole-1  |  == 
docker-pi-hole-pihole-1  | \5 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \6 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \7 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \8 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \9 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\0 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\1 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\2 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\3 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\4 ]]
docker-pi-hole-pihole-1  | + [[ 16 == \1\5 ]]
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Thanks, I'll take a look at this later on. In the meantime, could you rebase on `development-v6` and _maybe_ look at adding some tests for this section of code? Not sure about testing the db upgrade part, but the other parts should be testable

**Comment by PromoFaux** [comment]
@edgd1er , looks like you rebased on the wrong branch :)

**Comment by PromoFaux** [comment]
I have now merged the UID/GID branch in, so please rebase on development-v6 once more (I can do this for you if you need help!)

**Comment by edgd1er** [comment]
> I have now merged the UID/GID branch in, so please rebase on development-v6 once more (I can do this for you if you need help!)

I've rebased and signed off. it should be ok, now

File: src/start.sh [hunk 1]
```diff
@@ -101,16 +101,25 @@ sed -i "s/59 17/$((1 + RANDOM % 58)) $((12 + RANDOM % 8))/" /crontab.txt
...
-if [ -z "$SKIPGRAVITYONBOOT" ] || [ ! -f "${gravityDBfile}" ]; then
-    if [ -n "$SKIPGRAVITYONBOOT" ];then
-        echo "  SKIPGRAVITYONBOOT is set, however ${gravityDBfile} does not exist (Likely due to a fresh volume). This is a required file for Pi-hole to operate."
-        echo "  Ignoring SKIPGRAVITYONBOOT on this occaision."
-    fi
+if [ -n "${SKIPGRAVITYONBOOT}" ]; then
+  if [ -f "${gravityDBfile}" ]; then
+    #skip set + file =>update if needed
+    echo "  Skipping Gravity Database Update."
+    source /opt/pihole/utils.sh
```
Comment (PromoFaux) [inline src/start.sh:110]: What is `utils.sh` being sourced for here?

Comment (edgd1er) [reply src/start.sh:110]: > What is `utils.sh` being sourced for here?

At a time, I found it was mandatory, but now I commented it and it's not anymore needed.... I guess it can be removed.

on a side note, return is not allowed when not in a function: (uid/gid changes).
`[[ ${currentId} -eq ${PIHOLE_UID} ]] && return`

Comment (PromoFaux) [reply src/start.sh]: Thanks, good catch, I'll address that in a follow up PR (I should have waited for a review really, but.. sometimes I am impatient)

**Review by PromoFaux — APPROVED** [review]
